variables:
  DEBUG: "1"

.test_job:
  image: debian:bullseye
  tags:
    - docker
  artifacts:
    expire_in: 1 day
    paths:
      - sources
  before_script:
    - apt update -y && apt -y upgrade && apt install -y git mmdebstrap in-toto python3-pip python3-requests python3-apt python3-debian python3-dateutil python3-setuptools python3-rstr debian-keyring debian-archive-keyring
    - pip3 install -U python-debian
  script:
    - tests/run.sh $BUILDINFOS
  after_script:
    - mv /tmp/sources $CI_PROJECT_DIR/

binnmu-unrepr:
  extends: .test_job
  variables:
    BUILDINFOS: tests/data/0xffff_0.8-1+b1_amd64.buildinfo.unreproducible

debian-repr:
  extends: .test_job
  variables:
    BUILDINFOS: tests/data/gzip_1.10-2_all-amd64-source.buildinfo

qubes-repr:
  extends: .test_job
  variables:
    BUILDINFOS: tests/data/qubes-dnf_4.5.2-1+deb11u1_amd64.buildinfo

http-qubes-repr:
  extends: .test_job
  variables:
    BUILDINFOS: https://deb.qubes-os.org/r4.1/vm/pool/main/q/qubes-gui-agent/qubes-gui-agent_4.1.15-1+deb11u1_amd64.buildinfo

apt-amd64:
  extends: .test_job
  variables:
    BUILDINFOS: https://buildinfos.debian.net/buildinfo-pool/a/apt/apt_2.2.0_amd64.buildinfo

debian-root-fails:
  extends: .test_job
  variables:
    BUILDINFOS: https://buildinfos.debian.net/buildinfo-pool/t/tar/tar_1.34+dfsg-1_amd64.buildinfo

debian-buildpath:
  extends: .test_job
  variables:
    BUILDINFOS: https://buildinfos.debian.net/buildinfo-pool/a/acorn/acorn_8.0.5+ds+~cs19.19.27-1_all.buildinfo

# fixme: this is still failing due to upgrade
#debian-downgrade:
#  extends: .test_job
#  variables:
#    BUILDINFOS: https://buildinfos.debian.net/buildinfo-pool/a/appconfig/appconfig_1.71-2.1_all.buildinfo

metasnap-binnmu-unrepr:
  extends: .test_job
  variables:
    DEBIAN_OPTS: "--use-metasnap"
    BUILDINFOS: tests/data/0xffff_0.8-1+b1_amd64.buildinfo.unreproducible

metasnap-debian-repr:
  extends: .test_job
  variables:
    DEBIAN_OPTS: "--use-metasnap"
    BUILDINFOS: tests/data/gzip_1.10-2_all-amd64-source.buildinfo

debian-keyrings:
  extends: .test_job
  variables:
    BUILDINFOS: https://buildinfos.debian.net/buildinfo-pool/r/ruby-rails-dom-testing/ruby-rails-dom-testing_2.0.3-3_all.buildinfo
